export const mockCampaign = {
    'is_cpc': 'n',
    'click_extra_modules': null,
    'recurring_payment_setup': 'y',
    'meta_field_values_total_limit': 100,
    'tracking_type': 'standard',
    'conversion_type': 'sale',
    'is_cpc_default': null,
    'enable_publisher_accept_email': 'n',
    'vertical_id': 9,
    'hidden_campaign': 'n',
    'insight_clicktrail': 'y',
    'conversion_hiatus_period': 7,
    'allow_variable_sale_type': 'n',
    'attribution_fractional_commissioning': 'n',
    'insights_only_approved': 'y',
    'next_budget_summary_scheduled': null,
    'insight_sankey': 'y',
    'terms': null,
    'payment_date': null,
    'force_approve_period': 0,
    'commissions': [],
    'vat_status': 'standard',
    'campaign_communication_contact': null,
    'retire_reason': null,
    'created': '2011-05-20 12:56:21',
    'block_click_meta_to_conversion': 'y',
    'group_limited_by_field_value': null,
    'tracking_method': 'pixel',
    'default_override': 0,
    'click_extra_module_variables': null,
    'insight_conversiontime': 'y',
    'invoice_address_postcode': null,
    'associated_campaigns': null,
    'campaign_id': 300659,
    'reporting_timezone': 'Europe/London',
    'campaign_overloads': [],
    'invoice_company': null,
    'allow_deep_linking': 'y',
    'override_basket_value': null,
    'invoice_template': 'GB',
    'campaign_languages': null,
    'lead_confirmation_url_success': '',
    'override': 'n',
    'cpc_conversion_override_percentage': null,
    'force_reject_period': null,
    'hide_hybrid_from_publisher': 'n',
    'cookie_status': null,
    'commission_by_meta_label': 'Commission by Meta',
    'invoice_contact': null,
    'created_by': 3,
    'post_impression_tracking': 'n',
    'default_currency': 'GBP',
    'advertiser_id': 1,
    'conversion_extra_modules': null,
    'deferred_lead_submission': null,
    'destination_url_lang': null,
    'test_mode': 'n',
    'cost_per_lead': null,
    'pay_publisher_directly': 'n',
    'creative_remote_hosting': 'n',
    'invoice_backing_sheet_custom_fields': null,
    'containertag_extra_modules': null,
    'ignored_vouchers': null,
    'prepend_url_string': null,
    'last_modified': null,
    'campaign_communication_locale': null,
    'campaign_notes': '',
    'direct_linking': 'n',
    'status': 'a',
    'override_value_currency': 'n',
    'creative_alt_text': null,
    'commission_value_currency': null,
    'insight_repeatcustom': 'y',
    'commission_retirement_period': 0,
    'invoice_address_1': null,
    'campaign_budget': null,
    'vertical_name': 'Referral',
    'autoapprove_extra_module_variables': null,
    'log_untracked_conversions': 'n',
    'lead_confirmation_url_fail': '',
    'invoice_address_2': null,
    'network_fee': null,
    'multiple_conversions_per_click': 'y',
    'invoice_address_3': null,
    'default_commission_rate': null,
    'country': null,
    'invoice_address_4': null,
    'creative_retirement_period': 0,
    'week_start': 'monday',
    'group_limited_by_field': null,
    'autoapprove_extra_modules': null,
    'meta_field_values_field_limit': 10,
    'title': 'Carbon Offset',
    'budget_summary_interval': null,
    'associated_campaign_master': null,
    'associated_campaigns_mode': 'conversion',
    'conversion_allocation_mode': 'standard',
    'invoice_address_country': null,
    'app_tracking_integration_mapping': null,
    'commission_by_meta': 'value',
    'override_based_on_field': 'publisher_commission',
    'restricted_deep_linking': 'n',
    'containertag_extra_module_variables': null,
    'extra_restricted_deep_linking_domains': null,
    'auto_approve_publisher': 'n',
    'campaign_logo': '',
    'auto_rejected_ips': null,
    'hash_ip_addresses': 'n',
    'enable_publisher_reject_email': 'n',
    'campaign_invoice_locale': null,
    'default_commission_value': 1,
    'unique_conversion_refs': 'y',
    'app_tracking_provider': null,
    'dont_consolidate': 'n',
    'conversion_extra_module_variables': null,
    'consolidate_invoices': 'n',
    'lead_form_visible_publishers': 'y',
    'tracking_subdomain': null,
    'description': [],
    'cookie_period': 2592000,
    'associated_campaign_subjects': null,
    'budget_summary_start_time': null,
    'ip_tracking_time': 0,
    'commission_tiers': 'n',
    'robot_click_record': 'ignore',
    'background_process': 'n',
    'invoice_only': null,
    'destination_url': 'https://www.performancehorizon.com',
    'campaign_currency_conversions': [],
    'creative_prepend': null,
    'app_tracking_provider_tracking_link': null,
    'override_value': 'n',
    'broker_select_method': 1,
    'dont_invoice': 'n',
    'vat_number': null,
    'allow_third_party_pixel': 'n',
    'append_url_parameters': null,
    'secure_tracking': 'y',
    'tq_auto_approve': 60,
    'tq_enabled': 'n'
};

export const mockIncidents = [
    {
        'id': '1001l1235',
        'incident_type': 'volume_conversions',
        'context': {
            'id': '10',
            'scope': 'publisher'
        },
        'occurred_at': '2019-10-01',
        'publisher': {
            'id': '10',
            'name': 'APCOA'
        },
        'threshold': 500,
        'value': 660,
        'time_window': 7
    },
    {
        'id': '123',
        'incident_type': 'volume_clicks',
        'context': {
            'id': '10',
            'scope': 'publisher'
        },
        'occurred_at': '2019-06-03',
        'publisher': {
            'id': '10',
            'name': 'APCOA'
        },
        'threshold': 1.5,
        'value': 1.93662,
        'time_window': 7
    },
    {
        'id': '1001l1234',
        'incident_type': 'volume_conversions',
        'context': {
            'id': '1',
            'scope': 'publisher'
        },
        'occurred_at': '2019-01-03',
        'publisher': {
            'id': '1',
            'name': 'Leadsbox'
        },
        'threshold': 1.5,
        'value': 2.4342,
        'time_window': 1
    }
];
